Remove Autoinstall

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18,7 +18,7 @@ version="1.0.0"
 license="MIT/Expat (LICENSE)"
 
 authors="Chanku/Sapein" #Add in a comma in the string (an example: "Chanku/Sapein, Author 2, Author 69")
-options="help silent musl test posix autoinst install lib include libc c89_compat livesplit os"
+options="help silent musl test posix install lib include libc c89_compat livesplit os"
 compilers="gcc clang cc"
 
 implemented="(Not Implemented)"
@@ -458,119 +458,6 @@ stdlibs_compiler_gcc() {
 }
 
 
-autodl() {
-    libs=${1:-all}
-    libset=${2:-"$REQLIBS $OPTLIBS"}
-    case "$libs" in
-        livesplit_core)
-            if [ "$dl_prog" = "wget" ]
-            then
-                wget "$livesplit_url"
-                file_name=$(echo livesplit*)
-                mkdir livesplit
-                mv "$file_name" livesplit/
-                : "$(cd livesplit; tar -xzvf "$file_name")" #currently won't work for Windows
-                SC_INCLUDE_PATH="$SC_INCLUDE_PATH:$(pwd)/livesplit/bindings"
-                SLD_LIBRARY_PATH="$SLD_LIBRARY_PATH:$(pwd)/livesplit"
-                SLIBRARY_PATH="$SLIBRARY_PATH:$(pwd)/livesplit"
-            elif [ "$dl_prog" = "curl" ]
-            then
-                curl -o "$livesplit_url" livesplit.tar.gzip
-                mkdir livesplit
-                mv livesplit.tar.gzip livesplit/ #*nixen specific
-                : "$(cd livesplit; tar -xzvf "$file_name")" #currently won't work for windows
-                SC_INCLUDE_PATH="$SC_INCLUDE_PATH:$(pwd)/livesplit/bindings"
-                SLD_LIBRARY_PATH="$SLD_LIBRARY_PATH:$(pwd)/livesplit"
-                SLIBRARY_PATH="$SLIBRARY_PATH:$(pwd)/livesplit"
-            fi
-            ;;
-        b64)
-            t_USE_GIT="$USE_GIT"
-            if [ "$USE_GIT" -eq 2 ] && [ "$HAS_GIT" -eq 0 ]
-            then
-                while 0
-                do
-                    printf "Do you use to use git to download the base64 library [y/N]? "
-                    read -r r_t_USE_GIT
-                    original_r_t_USE_GIT="$r_t_USE_GIT"
-                    slice_output="%!@(*(..."
-                    slice_string "$r_t_USE_GIT" 0 1 0
-                    t_USE_GIT="$slice_output"
-                    USE_GIT=$(echo "$t_USE_GIT" | tr '[:upper:]' '[:lower:]')
-                    if [ "$t_USE_GIT" = "y" ]
-                    then
-                        USE_GIT=0 #use git
-                        break
-                    elif [ "$t_USE_GIT" = "n" ]
-                    then
-                        USE_GIT=1 #don't use git
-                        break
-                    elif [ "$t_USE_GIT" = "%!@(*(..." ]
-                    then
-                        printf "ERROR: STRING SLICING IS FAILING, PLEASE REPORT!\\n" 1>&2
-                        printf "Original raw_input: %s\\n" "$original_r_t_USE_GIT" 1>&2
-                        printf "Sliced Output: %s\\n" "$r_t_USE_GIT" 1>&2
-                        printf "Lowercase Output: %s\\n" "$t_USE_GIT" 1>&2
-                        printf "I, for one, welcome our non-string splitting overlords, preventing DLing is fun!!\\n" 1>&2
-                        t_USE_GIT=1
-                        break
-                    else
-                        printf "Unknown Input! Try again. \\n"
-                    fi
-                done
-            fi
-            if [ "$t_USE_GIT" -eq 0 ] && [ "$HAS_GIT" -eq 0 ]
-            then
-                printf "Clonging Brad Conte's base64 libraries!\\n"
-                git clone https://github.com/B-Con/crypto-algorithms.git opensplit-core/deps/crypto-algorithms
-            elif [ "$dl_prog" = "wget" ]
-            then
-                wget https://github.com/B-Con/crypto-algorithms/archive/master.zip
-                cp master.zip opensplit-core/deps/
-                command -v unzip
-                if [ $? -eq 0 ]
-                then
-                    : $(cd opensplit-core/deps; unzip master.zip; rm master.zip; mv crypto-algorithms-master/ crypto-algorithms/)
-                else
-                    rm master.zip
-                    echo "ERr"
-                    exit 1
-                fi
-            elif [ "$dl_prog" = "curl" ]
-            then
-                curl -o https://github.com/B-Con/crypto-algorithms/archive/master.zip master.zip
-                cp master.zip opensplit-core/deps/
-                : $(cd opensplit-core/deps; unzip master.zip; rm master.zip; mv crypto-algorithms-master/ crypto-algorithms/)
-            fi
-            ;;
-        criterion)
-            if [ $C89_COMPAT -eq 1 ]
-            then
-                command -v unzip
-                [ "$dl_prog" = "wget" ] && :
-                [ "$dl_prog" = "curl" ] && :
-            fi
-            ;;
-        marked)
-            IFS=$(printf ' \n\t')
-            for marked in $libraries_to_download
-            do
-                autodl "$marked"
-            done
-            IFS="$IFS_DEFAULT"
-            ;;
-        all)
-            IFS=$(printf ' \n\t')
-            for req in $libset
-            do
-                autodl "$req"
-            done
-            IFS="$IFS_DEFAULT"
-            ;;
-    esac
-
-}
-
 find_required_libs() {
     IFS=$(printf ' \n\t')
     case "$COMPILER" in
@@ -582,18 +469,12 @@ find_required_libs() {
                 then
                     printf " Found!\\n"
                 else
-                    if [ "$AUTO_INSTALL" -eq 0 ]
+                    printf " Not Found!\\n"
+                    if [ "opensplit-core/deps/crypto_algorithms/base64" = "$req" ]
                     then
-                        printf " Not Found...Marking for Auto-Install!\\n"
-                        libraries_to_download="$libraries_to_download $req"
-                    else
-                        printf " Not Found!\\n"
-                        if [ "opensplit-core/deps/crypto_algorithms/base64" = "$req" ]
-                        then
-                            printf "Please run clone_dependencies.sh to setup!\\n"
-                        fi
-                        exit 1
+                        printf "Please run clone_dependencies.sh to setup!\\n"
                     fi
+                    exit 1
                 fi
             done
             ;;
@@ -815,50 +696,12 @@ dl_check () {
 environment_check () {
     output=""
     set +eu
-    printf "Running Sanity Checks...\\n"
-    if [ "$AUTO_INSTALL" -eq 0 ]
-    then
-        printf "Checking Auto-Downloading\\n"
-        dl_check
-        printf "Done! "
-        #Check new value of auto-install
-        if [ "$AUTO_INSTALL" -eq 0 ]
-        then
-            if [ "$HAS_GIT" -eq 0 ] && [ "$USE_GIT" -eq 0 ]
-            then
-                output="Using git, and falling back to"
-                [ "$dl_prog" = "wget" ] && output="$output wget"
-                [ "$dl_prog" = "curl" ] && output="$output curl"
-            elif [ "$HAS_GIT" -eq 0 ] && [ "$USE_GIT" -eq 2 ]
-            then
-                output="Prompting for git, and falling back to "
-                [ "$dl_prog" = "wget" ] && output="$output wget"
-                [ "$dl_prog" = "curl" ] && output="$output curl"
-            elif [ "$dl_prog" = "wget" ]
-            then
-                output="Using wget!"
-            elif [ "$dl_prog" = "curl" ]
-            then
-                output="Using curl!"
-            fi
-        else
-            output="Auto-Downloading has been disabled!"
-        fi
-        printf "%s\\n" "$output"
-    fi
+    printf "Runnin$ Sanity Checks..."
+    printf "Done\\n"
     set -eu
 }
 
-disable_autodl () {
-    if [ "$AUTO_INSTALL" -eq 0 ]
-    then
-        printf "Disabling Auto-Downloading because Auto-DL functionality isn't complete.\\n"
-        AUTO_INSTALL=1
-    fi
-}
-
 command_line_parse "$@"
-disable_autodl
 environment_check
 
 # AUTODETECT MODE BEGIN
@@ -889,10 +732,6 @@ case $INTERFACE_MODE in
             else
                 livesplit_url=$(printf "%s" "$livesplit_url" | sed 's/LIBC/gnu/')
             fi
-        fi
-        if [ "$AUTO_INSTALL" -eq 0 ]
-        then
-            autodl "marked"
         fi
         . "./.configure_linux"
         ;;
